layout_spectrum: 0.9080944
name: inlingua
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.07379133
  lightness: 0.7849916
  saturation: 0.8288364
  rhythmicContrast: 0.9856661
  brandColors:
    - '#000000'
    - '#9B9C99'
    - '#5D301F'
    - '#A3654B'
    - '#EBEADF'
typography_spectrum: 0.6298482
